### ISSUE TITLE
IE7/IE8 Fail to open hash-trailed URL when in new tab (or followed link)

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#103] opened 2010-11-08 03:45 UTC
This is a strange one. Open a new tab and use this URL: http://www.publicintegrity.org/treesaver/tuna/#

Will fail to load the page at all (can't debug).

Remove the hash, page loads fine. Refresh an already loaded page with that URL, also fine. No idea here.

**Comment by bramstein** [comment] 2010-11-27 21:20
I can't reproduce this in either IE7 or 8 (both XP/SP3.) Is this still a problem for you?

**Comment by fortes** [comment] 2010-11-28 22:08
Still happening for me, however only when I create a page with that URL as the link and click on the link. Very strange.

**Comment by bramstein** [comment] 2010-11-28 22:39
When I do that, I get an "Operation Aborted" error in IE8. I'll look into it and see if I can find out why (usually related to modifying the DOM before it is ready.)

**Comment by bramstein** [comment] 2010-11-29 21:04
What version of the treesaver code-base is the Tuna edition using? I tried running it with the latest version, but get all sorts of scary JavaScript errors.

**Comment by fortes** [comment] 2010-11-29 21:18
Unfortunately, it's a fairly old version back from when it launched (hasn't been updated, as far as I can tell). I had a compiler bug in there as well which probably didn't help much.

Just pushed that fix. Are you able to work with what is in the Dropbox?

**Comment by bramstein** [comment] 2010-11-29 22:05
Ah, I was just trying to debug that :) Thanks for the fix. It seems there are some other problems, I'm not sure if they are due to recent changes or the combination of old markup with new code. I'll investigate a bit more.

**Comment by bramstein** [comment] 2010-11-30 22:45
Just to keep you updated. I haven't made much progress on this yet. It seems the application has some problems loading the cover page because getPages returns null (the 'Page ignored during pagination and article terminated' is written to the console.) Other pages load fine.

**Comment by fortes** [comment] 2010-12-01 03:16
Does that `getPages` issue happen on all IE loads, or just when there is a '#' at the end of the URL?

**Comment by bramstein** [comment] 2010-12-01 21:04
It seems to only happen on the cover page. Strangely enough, it only fails when I use the compiled and bundled version (both in debug and minification mode.) The dynamically loaded development version doesn't exhibit the same problems.

**Comment by fortes** [comment] 2010-12-01 22:35
Hm, might be a timing issue. Perhaps the initial layout is happening with a target size of zero, such that no content can ever fit. IE might be reporting the incorrect size at first.

But that wouldn't explain why the # in the url makes a difference here.

**Comment by bramstein** [comment] 2010-12-02 23:24
Some progress: turns out they are two separate issues, the JavaScript errors are caused by IE not recognizing HTML5 elements (article, figure, etc.) I added a script element with `document.createElement('article'); ...` and things load as they should. My guess is that the HTML5 shiv isn't loaded quickly enough.

The other problem ("Operation aborted") seems to occur when a second call to `processResourceFile` is made. I'll investigate some more on this one.

**Comment by fortes** [comment] 2010-12-03 11:36
There is already a script that does the create element work -- see `src/lib/html5.js` -- is there a bug in that script?

**Comment by bramstein** [comment] 2010-12-03 11:47
I don't think there is a bug, it just seems it isn't called early enough. (...) Actually I just checked and it seems the the contents of the file is compiled out (I guess it is not called elsewhere, hence dead code removal is triggered.) That definitely explains that problem :)

**Comment by bramstein** [comment] 2010-12-03 23:23
Definitively dead code removal going on here. It just reduces the contents of `src/lib/html5.js` to the conditional comment inside the `eval`. I guess to keep it from being removed we should move the whole HTML5 shiv inside an `eval` (unless you have a better idea.)
    eval("/_@cc_on'abbr article aside audio canvas details figcaption figure footer header hgroup mark meter nav output progress section summary time video'.replace(/\w+/g,function(n){document.createElement(n)})@_/")

(I took the shiv from: http://code.google.com/p/html5shim/)

**Comment by fortes** [comment] 2010-12-04 18:22
Interesting, I'm amazed it wasn't caught earlier. Closure compiler is powerful, but definitely dangerous.

Works for me, just wrap it in a `SUPPORT_IE` check so it compiles out.

**Comment by bramstein** [comment] 2010-12-07 23:30
I'm fairly certain the "Operation Aborted" error message is due to IE firing readystate events too early causing some of the early DOM manipulations to fail. Such failures usually happen in parsing articles or drawing the loading screen.

**Comment by fortes** [comment] 2010-12-08 15:20
Interesting -- why would it only happen when there is a trailing hash in the URL?

Any way we can work around the problem? Wait for onload in IE?

**Comment by bramstein** [comment] 2010-12-08 23:05
As far as I can tell the only difference between a page load with a hash and one without, is a call to `_changeState` and `replaceLocationHash_` The load sequence without a hash also has its `document.readyState` set to `complete`, while the load sequence with a hash usually reports `interactive`.

My current theory is that this is a timing related issue that only happens when the URL already contains a hash (either the extra code gives the DOM more time, or it somehow forces it to load.) Load sequences with hashes fail with an empty cache, but succeed afterwards (I assume the page is in the cache then.) I could be completely wrong about this, it is quite hard to debug when it only happens some of the time, and in different locations. :)

I'm planning to see if waiting for `onload` in IE improves this situation.

**Comment by bramstein** [comment] 2010-12-11 22:25
Just spent a couple more hours on this. I tried waiting for the `onload` event, but that didn't seem to solve the problem.

I really think this is a timing related issue. Just adding a couple of strategically placed console.log / alerts "fixes" the problem, or moves the bug to a later called piece of code. Why this only happens when there is a hash in the URL is a bit mysterious, it is hard to debug if debugging affects the bug, timing and location. Perhaps it is a completely unrelated problem, but I think it is probably related to: http://support.microsoft.com/kb/927917 and http://blogs.msdn.com/b/ie/archive/2009/09/03/preventing-operation-aborted-scenarios.aspx

**Comment by bramstein** [comment] 2011-03-26 10:43
I think I just stumbled upon the solution for this:

http://www.kontain.com/fi/entries/116938/operation-aborted-solved/

Tried it out, and it works! We should probably document this somewhere.

**Comment by bramstein** [comment] 2011-03-27 20:03
I've added this to the FAQ. Closing this ticket, and doing a little happy dance.

**Closed as completed by bramstein** 2011-03-27 20:03 UTC
