### ISSUE TITLE
chrome drops content on rescale

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#44] opened 2010-10-18 17:47 UTC
when rescaling the chrome to a different size all the content drops.

**Comment by fortes** [comment] 2010-10-19 00:10
Do you mean the TOC content?

**Comment by bramstein** [comment] 2010-10-27 11:26
I can't reproduce this on either Chrome or Firefox. Could you explain the problem in a bit more detail together with the browser and operating system you used?

**Comment by scottkellum** [comment] 2010-10-27 14:12
Sorry, I mean the TOC content.

So when class="chrome no-small" loads the TOC shows up fine. When resized to fit class="chrome small" all the microdata for the TOC in the sidebar seems to be lost. Nothing shows up in the side bar aside from the empty template. When scaled back up the content is still lost and is not retrieved until refresh.

**Comment by bramstein** [comment] 2010-10-27 19:14
Thanks! That helped me track down the problem. It should be fixed now in revision 7aeb38a.

**Closed as completed by bramstein** 2010-10-27 19:14 UTC
