### ISSUE TITLE
photostory intro

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#115] opened 2010-11-13 17:26 UTC
Having trouble keeping the photostory intro text in one place. required isn't forcing it to show up and no-page-1 is keeping things from being the first page, but all following text doesn't show up.

Note this happens on all photostorys in all verticals at all sizes where the text flows beyond the first page.

**Comment by fortes** [comment] 2010-11-13 18:57
Duplicate of #60. Closing

**Closed as completed by fortes** 2010-11-13 18:57 UTC
