### ISSUE TITLE
Not working on FF3.6 in OSX

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#50] opened 2010-10-20 14:45 UTC
Chrome and loading grid flash on screen shortly, then the page goes blank.

**Comment by scottkellum** [comment] 2010-10-20 14:57
problems if FF4 as well, but Chrome elements remain on screen. when cycling through articles you can eventually get it to work.

**Comment by scottkellum** [comment] 2010-10-22 18:25
Working in FF3.6 now but tends to get stuck in a loop on a single article.

**Comment by bramstein** [comment] 2010-10-31 21:23
Is this still a problem? I can't reproduce it (FF3.6)

**Comment by scottkellum** [comment] 2010-11-01 15:55
Managed to get the article loop.
Paged through to a feature article, refreshed, and couldn't get past the article I refreshed on.

**Comment by fortes** [comment] 2010-11-05 18:04
Getting a report of an infinite loop in the ICIJ right now on FF 3.6. Not sure if it's related. Needs investigation.

**Comment by fortes** [comment] 2010-11-05 22:00
Can't repro either of these issues. Tried all sorts of Firefox versions and combinations of situations. ICIJ can't repro anymore either.

Closing. If this comes up again, save out the HTML and create a new ticket.

**Closed as completed by fortes** 2010-11-05 22:00 UTC
