### ISSUE TITLE
Firefox & line-height

### ISSUE THREAD

**Issue by scottkellum** [Treesaver/treesaver#266] opened 2011-10-14 14:51 UTC
When NOT using a whole number for line-height in FireFox. The line-height gets set to 1px.

For example if the line-height is 1.3em, then FireFox will turn the line-height to 1px.

**Comment by mattguest** [comment] 2011-12-08 22:05
I found that Firefox seems to work with half numbers as well (1.5, 2.5, etc)

**Comment by andreacampi** [comment] 2012-08-28 05:32
I cannot reproduce this bug; I will give it some more time and then close it.

**Comment by andreacampi** [comment] 2012-10-02 08:16
As I wrote I cannot reproduce it; it's also likely that the behavior has been changed by the recent Chrome fixes.

**Closed as completed by andreacampi** 2012-10-02 08:16 UTC
Labels: Bug, pending deletion
