### ISSUE TITLE
Incorrect layouts when using browser zoom in Chrome/Safari

### ISSUE THREAD

**Issue by fortes** [Treesaver/treesaver#42] opened 2010-10-18 00:50 UTC
Webkit browsers do something strange with user-zoom, it completely messes up the measurement metrics.

**Comment by bramstein** [comment] 2010-11-05 22:02
This is a familiar problem to me (my line breaking implementation suffers from the same problem.) The problem is that scaling isn't reliable, for example, a 400 pixels wide block at 100% zoom, becomes 691 pixels wide at 172% zoom, while you would expect 688 pixels (400 \* 1.72)

**Comment by fortes** [comment] 2010-11-05 22:08
It seems like Firefox handles this in a more intelligent fashion, merely scaling the viewport and zooming the layout like a magnifying glass.

Let's not worry as much about the people who hit zoom after the document has loaded -- what is bad is someone who loads the page in a tab that was already zoomed, they end up with a terrible layout. I'm wondering if there's an easy fix to get the true metrics.

If there's no easy fix, let's push this out since it's not worthwhile.

**Comment by bramstein** [comment] 2010-11-05 22:30
I looked into a bit more, but I don't think there is an easy fix. I would love to be proven wrong on this though. Webkit seems to do some internal rounding of the values. There is some complaint here: http://hustoknow.blogspot.com/2010/10/chrome-and-jquery-ui-min-height-issue.html

But I haven't found much else. The basic problem is that when zoomed 1 + 1 does not equal 2 any longer. I think I'll move on to the other issues and get back to this later.

**Comment by fortes** [comment] 2010-11-05 22:34
Agreed, move on.

**Comment by fortes** [comment] 2011-03-17 03:05
I had an idea here about detecting zoom changes, which is actually an old technique that I used in a project years ago.

We could set up a visibility: hidden object with some text. We then query that object's size, watching for changes. If the users does browser zoom that causes the size to change, then we can force a re-measure. Will be a little slower, but should at least resolve issues with overlapping text.

However, this still won't resolve the primary issue of metrics being a bit off.

**Comment by bramstein** [comment] 2011-06-14 16:05
This bug report seems related: https://bugs.webkit.org/show_bug.cgi?id=60318

A fix is in progress!

**Closed as completed** 2011-12-14 00:01 UTC
Labels: Bug, pending deletion
